### ISSUE TITLE
Move `latexblock.tmLanguage.json` to `vscode/extensions/markdown-basics`

### ISSUE THREAD

**Issue by tamuratak** [jlelong/vscode-latex-basics#1]
We had better move `latexblock.tmLanguage.json` to `vscode/extensions/markdown-basics`. It should be a part of the built-in extension `markdown-basics`. 

https://github.com/jlelong/vscode-latex-basics/blob/915dddf9753639b0d35332253d5f6326340544ec/syntaxes/latexblock.tmLanguage.json

https://github.com/jlelong/vscode-latex-basics/blob/915dddf9753639b0d35332253d5f6326340544ec/package.json#L185-L195

**Comment by jlelong** [comment]
That would indeed make sense as the markdown grammar already defines fenced code block for many other languages. I guess we should make a PR on https://github.com/microsoft/vscode-markdown-tm-grammar.

**Comment by jlelong** [comment]
See the PR at microsoft/vscode-markdown-tm-grammar#99
