### ISSUE TITLE
Big pair matching

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#11]
Currently `\bigl...\bigr` are not matched as pairs but only the delimiters are matched (see the yellow colour for the first nesting level)

![Capture d’écran 2021-12-08 à 17 29 10](https://user-images.githubusercontent.com/2910140/145245847-29bc263e-ca4f-48c2-a52f-62cf293f4642.png)

I think we should define these as `brackets` entries in the `-language-configuration.json` files. 
@tamuratak What do you think?

**Comment by tamuratak** [comment]
I think it is a good idea.
