### ISSUE TITLE
More big bracket pairs with \langle...\rangle, \lvert...\rvert, \lVert...\rVert,, |, \|

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#13]
Originally posted by @matrix-ranger in https://github.com/James-Yu/LaTeX-Workshop/issues/3036

Consider adding the following bracket pairs

```
\langle ... \rangle
\lvert ... \rvert
\lVert ... \rVert
\left| ... \right| 
\left\vert ... \right\vert
\left\| ... \right\|
\left\Vert ... \right\Vert
\left\langle ... \right\rangle
\left\lvert ... \right\rvert
\left\lVert ... \right\rVert
\bigl\langle ... \bigr\rangle
\bigl| ... \bigr|
\bigl\vert ... \bigr\vert
\bigl\lvert ... \bigr\rvert
\bigl\| ... \bigr\|
\bigl\lVert ... \bigr\rVert
\bigl\Vert ... \bigr\Vert
\Bigl\langle ... \Bigr\rangle
\Bigl| ... \Bigr|
\Bigl\lvert ... \Bigr\rvert
\Bigl\vert ... \Bigr\vert
\Bigl\| ... \Bigr\|
\Bigl\lVert ... \Bigr\rVert
\Bigl\Vert ... \Bigr\Vert
\biggl\langle ... \biggr\rangle
\biggl| ... \biggr|
\biggl\lvert ... \biggr\rvert
\biggl\vert ... \biggr\vert
\biggl\| ... \biggr\|
\biggl\lVert ... \biggr\rVert
\biggl\Vert ... \biggr\Vert
\Biggl\langle ... \Biggr\rangle
\Biggl| ... \Biggr|
\Biggl\lvert ... \Biggr\rvert
\Biggl\vert ... \Biggr\vert
\Biggl\| ... \Biggr\|
\Biggl\lVert ... \Biggr\rVert
\Biggl\Vert ... \Biggr\Vert
```

The grammar files will also need to be updated according to microsoft/vscode#137774.

**Comment by matrix-ranger** [comment]
I can confirm that these are registered as bracket pairs in the updated version but two of them do not have the correct highlighting, namely \lvert ... \rvert and \lVert ... \rVert (all the others are correct).

<img width="704" alt="image" src="https://user-images.githubusercontent.com/48684632/162741618-36b19755-760e-4d15-b6a5-0a1480ebe354.png">

**Comment by jlelong** [comment]
I cannot reproduce the behaviour what you describe. Please open a new issue with the precise version of VS Code you are using.
