### ISSUE TITLE
Highlight Julia code

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#14]
Originally posted by @JamieMair in James-Yu/LaTeX-Workshop#3054

When I am using a package to enable proper typesetting of Julia code, the syntax highlighting does not use the Julia syntax highlighting, but the default latex highlighting. This is shown below:
![image](https://user-images.githubusercontent.com/13971435/149601532-7d1c2f89-1bae-441d-b701-8decba768276.png)
This becomes an issue when using special characters:
![image](https://user-images.githubusercontent.com/13971435/149601551-8529d278-02e4-427f-a592-e73ea9db8477.png)

## To Reproduce  [Required]

Insert code as shown above. This can be useful for the verbatim package as well.

**Comment by jlelong** [comment]
@JamieMair Can you post the tex content of your example? What packages are providing the environments `juliaconsole` and `juliaverbatim`?

**Comment by JamieMair** [comment]
I am using a copy of this template - https://github.com/sisl/tufte_algorithms_book

In the introduction.TeX file in the chapters, you can find examples of the Julia related environments working (there a few different ones). 

I believe they use a version of the pythontex package with a custom lexer to do the syntax highlighting in the PDF. As far as I can tell, the Julia latex environments are defined in pythontex.sty

Maybe it would be useful to have an optional setting in which you can specify the syntax highlighting for different environments. For example:
```json
"vscode-latex-basics.syntax.environments": {
    "juliaverbatim": ".jl"
    "juliaconsole": ". jl"
... Etc
}
```

**Comment by JamieMair** [comment]
Perhaps this line https://github.com/jlelong/vscode-latex-basics/blob/5f26a6daf70352a6f3f40b3b4437a605f5d954ee/syntaxes/LaTeX.tmLanguage.json#L466 needs to be modified to be like https://github.com/jlelong/vscode-latex-basics/blob/5f26a6daf70352a6f3f40b3b4437a605f5d954ee/syntaxes/LaTeX.tmLanguage.json#L485
Which has support for pythontex environments.

**Comment by JamieMair** [comment]
https://github.com/jlelong/vscode-latex-basics/pull/15 - The proposed changed seemed to work fine.

**Comment by jlelong** [comment]
Close by #15

**Comment by jlelong** [comment]
> Maybe it would be useful to have an optional setting in which you can specify the syntax highlighting for different environments. For example:
> 
> ```json
> "vscode-latex-basics.syntax.environments": {
>     "juliaverbatim": ".jl"
>     "juliaconsole": ". jl"
> ... Etc
> }
> ```


Unfortunately, it is not possible to use configuration variables in TextMate grammars. Only [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) can be configured by the user but for the time being we consider it out of the scope of the extension.
