### ISSUE TITLE
Exclude parentheses from bracket coloring

### ISSUE THREAD

**Issue by 8hur** [jlelong/vscode-latex-basics#18]
Outside of math environment, the matching of parenthesis doesn't really belong to the code part of the LaTeX language.
With the addition of [bracket pair colorisation](https://code.visualstudio.com/docs/editor/editingevolved#_bracket-pair-colorization) to VS Code, when enabled, parentheses in text section are colored, which I tend to find disturbing. I believe parentheses should be explicitly excluded from bracket pair colorization.

[This example](https://github.com/microsoft/vscode/blob/997228d528d687fd17cbf3ba117a0d4f668c1393/extensions/javascript/tags-language-configuration.json) shows how it could be done (by explicitly excluding the parentheses from the "colorizedBracketPairs" range.

**Comment by jlelong** [comment]
Bracket pair colorisation is really great for the math mode to immediately detect unbalanced pairs and I really want to keep it. Unfortunately, there is no way to deactivate bracket pair colorisation outside of the math mode.
