### ISSUE TITLE
`minted` code block matching for multiline options

### ISSUE THREAD

**Issue by frankli0324** [jlelong/vscode-latex-basics#22]
minted options would have to stay on the same line in order for code highlighting to work
https://github.com/jlelong/vscode-latex-basics/blob/4479589c0f5c21c7f5ef17551e1013ab72e7f718/syntaxes/LaTeX.tmLanguage.json#L156

A minimal example to reproduce the issue

<img width="343" alt="image" src="https://user-images.githubusercontent.com/20221896/168700984-8e1b7313-6071-490d-af27-e3e3d51706c2.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/20221896/168701195-7ce8adf0-f253-4cd6-b238-05710ef57a90.png">

- VS Code Version: seems irrelevant
- OS Version: MacOS 12.3.1, seems irrelevant
- LaTeX-Workshop version if you use it: v8.26.0

**Comment by jlelong** [comment]
VS Code uses the `textmate` engine for syntax highlighting. The rules are matched again a single line of the document at a time, which makes handling multi-line constructions very complicated. I will investigate this to see if we can accept multi-line options without coming with jeopardising  the maintenance of the grammar file.
