### ISSUE TITLE
Embedded Python code breaks syntax highlighting in the rest of the document

### ISSUE THREAD

**Issue by merlinND** [jlelong/vscode-latex-basics#27]
Hello,
First off, thanks a lot for your wonderful work on LaTeX tooling for VS Code.

I'm encountering an issue with embedded Python code (in a `minted` block) breaking syntax highlighting in the rest of the document. MWE:

```latex
\documentclass{article}
\usepackage{minted}
\begin{document}

\textbf{Syntax highlighting works fine above.}

\begin{minted}[escapeinside=||]{cpp}
    // No problem in the cpp syntax
    |$\epsilon$| = 1e-3
    (|$\epsilon$|)
    {|$\epsilon$|}
    [|$\epsilon$|]
    [|$\epsilon$|]
\end{minted}

\begin{minted}[escapeinside=||]{python}
    # No problem with these lines:
    |$\epsilon$| = 1e-3
    # (|$\epsilon$|)

    # Any of these lines trigger the bug as long
    # as they are not commented out.
    (|$\epsilon$|)
    {|$\epsilon$|}
    [|$\epsilon$|]
    [|$\epsilon$|]
\end{minted}

\textbf{Syntax highlighting is broken here.}

\end{document}
```

Here's how it looks with broken highlighting:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/5563370/177723685-bf316dd1-3f94-4708-a4ca-0f37fd2977f8.png">

And with highlighting repaired by commenting out the offending lines:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/5563370/177723797-3cd02eb1-c611-4bfa-88b6-2b28d464797f.png">

- VS Code Version: 1.68.1
- OS Version: macOS 11.6
- LaTeX-Workshop version if you use it: v8.27.2

I apologize if this is a broader VS Code issue and not related to the extension. Thanks for your help!

**Comment by jlelong** [comment]
The character `\` is the continuation line mark and must be followed by a line break. If it is not, then the Python syntax marks the rest as `invalid.illegal.line.continuation.python`. In `(|$\epsilon$|)`, the opening `(` is actually never closed from the Python syntax point of view of then `\end{minted}` is not detected.

I am afraid there is not much we can do here.

**Comment by merlinND** [comment]
I see, thank you for the explanations!

By any chance, do you know of another way to insert math inside of `minted` envs without breaking the syntax highlighting?

**Comment by merlinND** [comment]
After a bit of investigating, here's a viable workaround:
Use `\catcode` to locally redefine `!` as an escape character (equivalent to LaTeX's normal `\`).
Then, in the code snippet, use `!` instead of `\`.

This change can be automated:

```LaTeX
\BeforeBeginEnvironment{minted}{%
    \begingroup
        \catcode`\!=0
}
\AfterEndEnvironment{minted}{%
        \catcode`\!=0
    \endgroup
}
```
