### ISSUE TITLE
Highlight tabulararray redefined amsmath environments

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#37]
Originally posted by @Firestar-Reimu  in James-Yu/LaTeX-Workshop#3485

> With `\UseTblrLibrary{amsmath}` in the preamble of the document, `tabularray` will load `amsmath` package, and define `+array`, `+matrix`, `+bmatrix`, `+Bmatrix`, `+pmatrix`, `+vmatrix`, `+Vmatrix` and `+cases` environments. Each of the environments is similar to the environment without + prefix in its name, but has default rowsep=2pt just as tblr environment. Every environment except +array accepts an optional argument, where you can write inner specifications.

This is another issue besides #2851, relating to `tabularray` package

You can see that, after adding the `+` the highlight is wrong:

![Screenshot_20220918_235436](https://user-images.githubusercontent.com/65082432/190916191-d348f80a-a8d6-406c-9349-12e7de1baf27.png)

I used to think all `\begin` and `\end` pairs will be highlighted?

**Comment by Firestar-Reimu** [comment]
I think it is this line

```
https://github.com/James-Yu/LaTeX-Workshop/blob/ef04d42bb2e13b1381961163672ef8b734703fab/syntax/LaTeX.tmLanguage.json#L816
```

**Comment by jlelong** [comment]
There are two issues here

1. We currently only accept letters and an optional ending `*` for environments
2. You expect that the `+matrix` environment is recognized as a tabular environment, ie `&` is highlighted as a column separator.

**Comment by jlelong** [comment]
> I think it is this line
> 
> ```
> https://github.com/James-Yu/LaTeX-Workshop/blob/ef04d42bb2e13b1381961163672ef8b734703fab/syntax/LaTeX.tmLanguage.json#L816
> ```

See https://github.com/James-Yu/LaTeX-Workshop/tree/master/syntax#grammars-and-language-configuration-files

**Comment by Firestar-Reimu** [comment]
I changed that line and all syntax highlighting disappeared

**Comment by Firestar-Reimu** [comment]
Thanks! @jielong when will the users get this update?
