### ISSUE TITLE
Math delimiters `\(....\)` are not highlighted as pairs

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#42]
Originally posted in https://github.com/James-Yu/LaTeX-Workshop/discussions/3677

Inline maths delimiters `\(...\)` are not highlighted as pairs.

**Comment by jlelong** [comment]
@harrysw1729 @James-Yu 

Even if it looked a good idea at first sight, I think this is actually a bad idea.

Once delimiters are declared as a pair, we loose complete control of the highlighting, which is automatically handled by VS Code, when `editor.bracketPairColorization.enabled` is set. 

I made an attempt in https://github.com/jlelong/vscode-latex-basics/tree/42_escaped_parens_pair

<img width="234" alt="Capture d’écran 2023-02-01 à 08 28 01" src="https://user-images.githubusercontent.com/2910140/215978540-db50bab1-79be-420d-ab02-a0b270c961ca.png">

Note the following inconsistencies
- The pair `$ ... $` has the same scope as `\(...\)`but it is highlighted differently because `$...$` is not declared as a bracket pair.
- The color of `\(...\)` depends on its nesting level.

I think the cons are really out weighting the pros. So, I am closing this issue.

**Comment by RedCMD** [comment]
vscode is about to add the option to disable colouring on bracket pairs
https://github.com/microsoft/vscode/issues/170497

**Comment by jlelong** [comment]
@RedCMD Thanks for the link. I will keep an eye on it to see how to best modify our language configuration files.
