### ISSUE TITLE
Incorrect scope for utf8 characters in labels

### ISSUE THREAD

**Issue by Enivex** [jlelong/vscode-latex-basics#45]
![image](https://user-images.githubusercontent.com/2191754/220090599-5e3fc067-a475-4a32-b47a-8c9168c5e115.png)

ö does not get the "constant.other.reference.label.latex" that the other letters get

A minimal example to reproduce the issue

- VS Code Version: 1.75.1
- OS Version: W11
- LaTeX-Workshop version if you use it: 9.7.0

**Comment by jlelong** [comment]
This was because the regex class `\w` does not contains characters with accent. We know the `\p{Alphabetic}` utf-8 class.
