### ISSUE TITLE
decimal digits in \cite arguments are not highlighted

### ISSUE THREAD

**Issue by JLHwung** [jlelong/vscode-latex-basics#49]
VSCode fails to highlight the digits `1950` in `\cite{Turing1950}`.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/3607926/229966839-47c1930a-a36e-4e78-8cdf-bb964cb3a925.png">

A minimal example to reproduce the issue

`\cite{Turing1950}`

- VS Code Version: 1.74.3
- OS Version: macOS 12.1
- LaTeX-Workshop version if you use it: 9.8.2

This is likely a regression introduced in https://github.com/jlelong/vscode-latex-basics/commit/54c7cf6100e70052873a63510acebd83c5355667. Previously `\w` matches alphanumeric, "_" and multibyte char, but `\p{Alphabetic}` matches only "Lu + Ll + Lt + Lm + Lo + Nl + Other_Alphabetic". We can fix this using `\p{Alphabetic}\p{Number}`.

**Comment by jlelong** [comment]
Close by 2c4286c

**Comment by scaomath** [comment]
@jlelong Hi Jerome, when will this change be included in a new version of [James-Yu/LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop)?

**Comment by jlelong** [comment]
It will be included in the next release of LW.
