### ISSUE TITLE
Quote on multiple lines (with inner apostrophe in math mode) causes issues

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#61]
Originally posted by @gertab in James-Yu/LaTeX-Workshop#3939

When quote (``...'') is split over multiple lines and there is an apostrophe in math mode, the text following it loses its coloring scheme.

No problem for versions up to 9.11.4. However in versions **9.11.5** and upwards, there is this issue.

The following snippet reproduces the issue, where the bottom text loses its color scheme:

```latex
\documentclass{article}

\begin{document}

Original text

``This $x'$ is 
on the same line''

Bottom text and math symbols $x$

\end{document}

```

From the given example both `Original text` and `Bottom text and math symbols $x$` should be the same color.

**Comment by jlelong** [comment]
Related to #59

**Comment by gertab** [comment]
Thanks!
