### ISSUE TITLE
BibTeX syntax: "%" is not a comment character

### ISSUE THREAD

**Issue by zepinglee** [jlelong/vscode-latex-basics#64]
The percentage character is treated as inline comment in the current BibTeX syntax (see the [`percentage_comment`](https://github.com/jlelong/vscode-latex-basics/blob/3fdf10f2f31628a335ed7f26b709c037a3263457/syntaxes/Bibtex.tmLanguage.json#L329-L353)  rule, the [test entry](https://github.com/jlelong/vscode-latex-basics/blob/3fdf10f2f31628a335ed7f26b709c037a3263457/test/colorize-fixtures/test.bib#L20-L32) and [result](https://github.com/jlelong/vscode-latex-basics/blob/3fdf10f2f31628a335ed7f26b709c037a3263457/test/colorize-results/test_bib.json#L534-L545)). However it doesn't match BibTeX's behavior. The BibTeX [doc](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf) (§4, item 14, p. 14) says:

> LaTeX’s comment character ‘%’ is not a comment character in the database files.

And it's verified with the following example. 

Biber treats percentage characters differently (see <https://tex.stackexchange.com/a/262282/82731>) but I think it's more reasonable to be compatible with traditional BibTeX.

A minimal example to reproduce the issue

`main.tex`
```tex
\documentclass{article}

\bibliographystyle{plain}

% \usepackage{biblatex}
% \addbibresource{test.bib}


\begin{document}

\cite{glasbook}

\bibliography{test}

% \printbibliography

\end{document}
```

`test.bib`
```bibtex
@book{glasbook,
  author  = {Glasserman, Paul},
  title   = {Monte {C}arlo %methods in 
             financial engineering},
  series  = {Applications of Mathematics (New York)},
  %volume  = {53},
  note    = { Stochastic Modelling and Applied Probability},
  address = {New York},
  year    = {2004},
  pages   = {xiv+596},
  isbn    = {0-387-00451-3 {toto}},
  url     = {http://www.example.com/some-%AC-encoded-%2C-character}
}
```
<img width="568" alt="Screenshot 2023-08-12 at 10 53 35" src="https://github.com/jlelong/vscode-latex-basics/assets/12290822/3401a1dd-e2d9-4120-88cc-f09109a960a2">

BibTeX gives an error:
```
You're missing a field name---line 6 of file test.bib
 :   
 :   %volume  = {53},
```

If the line `%volume  = {53}` is deleted, BibTeX produces the following into the `.bbl` file in which the commented `}` causes a unmatched brace error in the next LaTeX run.

```tex
\begin{thebibliography}{1}

\bibitem{glasbook}
Paul Glasserman.
\newblock {\em Monte {C}arlo %methods in financial engineering}.
\newblock Applications of Mathematics (New York). New York, 2004.
\newblock Stochastic Modelling and Applied Probability.

\end{thebibliography}
```

```
./main.bbl:9: Missing } inserted.
<inserted text> 
                }
l.9 \end{thebibliography}
```

Biber ignores the line `%volume  = {53}` but produces the contents following the percentage character in `title` field into the `.bbl` output, which results in an error in the next run of latex.
```tex
      \field{title}{Monte {C}arlo %methods in financial engineering}
      \field{year}{2004}
      \field{pages}{xiv+596}
```

```
Runaway argument?
{Monte {C}arlo \field {year}{2004} \field {pages}{xiv+596} \range {pa\ETC.
./main.tex:9: File ended while scanning use of \field.
<inserted text> 
                \par 
l.9 \begin{document}
                    
./main.tex:9:  ==> Fatal error occurred, no output PDF file produced!
```

- VS Code Version: 1.81.1
- OS Version: macOS 13.4.1
- LaTeX-Workshop version if you use it: v9.13.4

**Comment by zepinglee** [comment]
Also note the PEG from <https://github.com/aclements/biblib> is worth reference. It's the most accurate to the original BibTeX AFAIK.

**Comment by jlelong** [comment]
Fair enough, I am reverting #46.

**Comment by zepinglee** [comment]
BTW, how can I generate the test results if when further contribute to the grammar (e.g., add `@preamble` support)?

**Comment by jlelong** [comment]
See https://github.com/jlelong/vscode-latex-basics#test

If a given fixture file does not have an associated test result file, it is automatically generated when running `npm test`.

**Comment by zepinglee** [comment]
> If a given fixture file does not have an associated test result file, it is automatically generated when running `npm test`.

I see. Thanks!
