### ISSUE TITLE
Syntax highlighting broken after German quotation marks

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#68]
Originally posted by @jfrerking in James-Yu/LaTeX-Workshop#4015

> Closely related to issue James-Yu/LaTeX-Workshop#593 . German quotation marks are often written as `text ,,quote`` text` in LaTeX. The syntax highlighting interprets everything after the closing marks (two back ticks) as a string and highlights it accordingly. One can circumvent the problem by using the csquotes package and writing `text \enquote{quote} text`, but it would be great, if the syntax interpreter treats ,,quote`` as a string, indicated by two commas not followed by any space (or ignores the two back ticks if they are not followed by '' anywhere?). 
> 
> (I agree with user stone-zeng in issue James-Yu/LaTeX-Workshop#593 that string highlighting seems unnecessary in tex-files generally, but understand if disabling it altogether is not possible.)

**Comment by jlelong** [comment]
This is caused by #59. I will try to fix the grammar and if I can't figure it out I will disable quote highlighting.

**Comment by jfrerking** [comment]
Thank you!
