### ISSUE TITLE
Syntax bug when quotations mixed with comments or math

### ISSUE THREAD

**Issue by zepinglee** [jlelong/vscode-latex-basics#70]
The current grammar produces incorrect syntax with quotes mixed with comments or math.

<img width="300" alt="Screenshot 2023-10-22 at 17 19 07" src="https://github.com/jlelong/vscode-latex-basics/assets/12290822/afa2ff26-dc79-4f25-841b-11ec094d6aa6">

A minimal example to reproduce the issue

```tex
``foo % comment
bar''

``Double quoted text with math $f''(x)$
and more text''
```

One possible solution is adding the following in the `string.quoted.double.latex` rule so that the contents within it are nested.
```
			"patterns": [
				{
					"include": "$base"
				}
			]
```

<img width="314" alt="Screenshot 2023-10-22 at 17 33 24" src="https://github.com/jlelong/vscode-latex-basics/assets/12290822/d5c15088-5c6f-446a-a4aa-b4a68a811030">

Alternatively, it may be unnecessary to highlight the quotations because they are plain text/symbols rather than string literals in TeX language.

- VS Code Version: 1.83.1
- OS Version: macOS 13.6
- LaTeX-Workshop version if you use it: v9.14.1

**Comment by jlelong** [comment]
I am a bit hesitating on this one. It looked great to highlight quoted string but I am afraid it will break rapidly as constructions become more complicated.  For instance, see https://github.com/James-Yu/LaTeX-Workshop/issues/4032 and #68.

All in all, I believe it is best to remove quotation highlighting.

**Comment by zepinglee** [comment]
> All in all, I believe it is best to remove quotation highlighting.

I also agree with this.
