### ISSUE TITLE
Non-existent `\merge` is highlighted the same as `\alpha` in math mode

### ISSUE THREAD

**Issue by muzimuzhi** [jlelong/vscode-latex-basics#71]
**A clear and concise description of what the bug is**

In math mode, non-existent command `\merge` is highlighted the same as `\alpha` and `\beta`. Other simple words like "split" and "hello" cannot reproduce the problem.

A direct search for "merge" in this repository gives no matches.

**A minimal example to reproduce the issue**

```tex
$\alpha \beta \merge \split \hello \apple$
```
<img width="580" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/6376638/461d3b9c-cf54-427c-a002-f52de8d99911">

**Version info**

- VS Code Version: 1.84.0 (all extensions disabled)
- OS Version: macOS 13.4.1
- LaTeX-Workshop version if you use it:

**Comment by zepinglee** [comment]
The `\merge` command matches the following rule.

https://github.com/jlelong/vscode-latex-basics/blob/221a2443a5e8ac029685a0f872af39b23cc2b634/syntaxes/TeX.tmLanguage.json#L156-L164

This pattern dates back to <https://github.com/textmate/latex.tmbundle/commit/2b1579515a5f75cf30a711d84d246c09f553a579> and it was rewritten in the current form in <https://github.com/textmate/latex.tmbundle/commit/95092d1fb73b5df15785e6961d2cca6082e6506b>.

**Comment by jlelong** [comment]
@zepinglee Thanks a lot for the reference!

Actually, I do not think this is a bug. The `\merge` command is provided by the `stmaryrd` package, see on top of page 2 of https://ctan.mines-albi.fr/fonts/stmaryrd/stmaryrd.pdf. This command is also part of _The Comprehensive LATEX Symbol List_ https://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf

**Comment by muzimuzhi** [comment]
I can confirm `\merge` is matched by this branch
```
"(...|m(ho|i(nuso|d)|o(o|dels)|u(ltimap)?|p|e(asuredangle|rge))|...)(?![a-zA-Z])"
      ^ m                                   ^ e           ^ rge
```
and `\merge` is provided by `stmaryrd` LaTeX package, see for example [`maths-symbols.pdf`](https://ctan.org/pkg/maths-symbols) (a predecessor of the [comprehensive symbols list](https://ctan.org/pkg/comprehensive)), Table 25.

I also checked other `stmaryrd` commands are matched as well, for instance the regex snippet `Y(down|up|left|right)`.

So the problem becomes, in which range the VScode LaTeX grammar should recognize commands only defined in LaTeX packages?

**Comment by muzimuzhi** [comment]
The case I originally encountered has been fixed in
- #72
