### ISSUE TITLE
Useless `"patterns"` array

### ISSUE THREAD

**Issue by RedCMD** [jlelong/vscode-latex-basics#73]
`"patterns"` array is only valid with a `"begin"` rule
not the `"match"` rule
it currently doesn't do anything

https://github.com/jlelong/vscode-latex-basics/blob/8806aaaec1a7e0e7a76505db6217b9ac9c97ba7d/syntaxes/markdown-latex-combined.tmLanguage.json#L2262

**Comment by jlelong** [comment]
The file `vscode-latex-basics/syntaxes/markdown-latex-combined.tmLanguage.json` is derived from https://raw.githubusercontent.com/microsoft/vscode/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json, which is a json version of https://github.com/microsoft/vscode-markdown-tm-grammar/blob/main/syntaxes/markdown.tmLanguage.

The bug should probably be filled against the `vscode-markdown-tm-grammar` repo
