### ISSUE TITLE
[Feature request] highlight `iffalse` block as a comment

### ISSUE THREAD

**Issue by ian-h-chamberlain** [jlelong/vscode-latex-basics#76]
Same as https://github.com/James-Yu/LaTeX-Workshop/issues/3972

Basically, it's common to use `\iffalse`...`\fi` blocks as a kind of multiline comment, since the contents of the block will not be rendered. As such, it would be nice to highlight these blocks as if they were comments.

Would it be feasible to add this as a "block comment" scope for this in the grammar? I have seen some other extensions do something similar with e.g. `#if 0` in C/C++ and I think it would be handy to easily see chunks of code that have been disabled this way.

Thanks!

**Comment by jlelong** [comment]
Thanks for your report. I will investigate how to best support `\iffalse`/`\fi`. 
A complete support would require to catch nested `\ifXXXX`/`\fi` and I am not sure how easily this can be achieved. The grammar is already very long and maintenance has become a main concern.

**Comment by ian-h-chamberlain** [comment]
Ah, interesting point about nesting and stuff, I hadn't considered that. I found this related issue which discusses some of the trade-offs and implementation: https://github.com/lervag/vimtex/issues/1988
Given the complexity I think this is not as simple of a task as I initially thought 😅 

Although that example is a vim `syntax`, I think the same idea applies — basically the `\iffalse` begin/end would include other conditionals in its body, for example the Rust syntax includes comments recursively to support nesting: https://github.com/microsoft/vscode/blob/main/extensions/rust/syntaxes/rust.tmLanguage.json#L295-L305

Does the grammar already include any `\if` / `\fi` special for beginning/ending blocks, or would that also need to be added for this?
