### ISSUE TITLE
 LaTeX and TeX highlighted incorrectly in Markdown

### ISSUE THREAD

**Issue by BearToCode** [jlelong/vscode-latex-basics#83]
## A clear and concise description of what the bug is.

LaTeX and TeX are highlighted incorrectly inside Markdown, they stop working after a `\section`(and also other commands) is used.
I'm not sure whether this issue is related more with this repo, or with the [markdown one](https://github.com/microsoft/vscode-markdown-tm-grammar/tree/main); I'll move the discussion there in case.

This is the rule that implements LaTeX in Markdown:

```xml
      <key>fenced_code_block_latex</key>
      <dict>
        <key>begin</key>
        <string>(^|\G)(\s*)(`{3,}|~{3,})\s*(?i:(latex|tex)((\s+|:|,|\{|\?)[^`]*)?$)</string>
        <key>name</key>
        <string>markup.fenced_code.block.markdown</string>
        <key>end</key>
        <string>(^|\G)(\2|\s{0,3})(\3)\s*$</string>
         // ...
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^|\G)(\s*)(.*)</string>
            <key>while</key>
            <string>(^|\G)(?!\s*([`~]{3,})\s*$)</string>
            <key>contentName</key>
            <string>meta.embedded.block.latex</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.tex.latex</string>
              </dict>
            </array>
          </dict>
        </array>
```

## A minimal example to reproduce the issue

Go into vscode and type the following(please unescape the backticks `)

```
\`\`\`latex
\begin{document}
    \maketitle

    \section{Hello World!} Highlighted correctly!
\end{document} No longer highlighted :(
\`\`\`
```

Result:
![snippet](https://github.com/jlelong/vscode-latex-basics/assets/47280851/e78942f0-bae1-46dd-996b-2c70c70d38b0)

- VS Code Version: 1.88.0
- OS Version: Windows 11

**Comment by zepinglee** [comment]
I can reproduce that. It seems the last `$base` in the following block causes the tokenizer enters `meta.paragraph.markdown` scope and fails to come out until the closing ` ``` `. Perhaps it should be changed to `$self`.

<img width="631" alt="Screenshot 2024-04-08 at 23 39 05" src="https://github.com/jlelong/vscode-latex-basics/assets/12290822/ad72bdd0-6852-43e5-a1db-73c0dab1ac66">

https://github.com/jlelong/vscode-latex-basics/blob/cf291a400201d1c0a857344fc82f05e7d8e57e69/syntaxes/src/LaTeX.tmLanguage.base.yaml#L46-L66

**Comment by jlelong** [comment]
@zepinglee Good catch. Thanks
