### ISSUE TITLE
LaTeX3/expl3 syntax highlight fails in environments

### ISSUE THREAD

**Issue by SwitWu** [jlelong/vscode-latex-basics#84]
### A clear and concise description of what the bug is.

LaTeX3/expl3 syntax highlight fails in environments.

### A minimal example to reproduce the issue

With this code snippet:
```tex
\int_case:nn
\begin{center}
  \int_case:nn
\end{center}
```
the output is
<img width="312" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/205f3242-48c9-4679-b844-b7e546dba4e3">

- VS Code Version: 1.88.1 (Universal)
- OS Version: macOS Sonoma 14.4.1
- LaTeX-Workshop version if you use it: latest

**Comment by jlelong** [comment]
This is related to the fix of #83. This is a tricky issue.

Consider the above example: the latex3 grammar calls the latex grammar and we would the content of an environment to be matched against the base grammar (latex3).

When latex is embedded in markdown for instance, we want the content of an environment to be matched against the latex grammar and not the base grammar (markdown)

I can think of two solutions
1. Duplicate the latex grammar to define the latex3 grammar but this is no good for maintenance
1. Integrate the specificity of latex3 into latex and use the same grammar all the time.

I think 2 is best. @James-Yu any opinion?

**Comment by James-Yu** [comment]
I would vote for the second option 😄

**Comment by jlelong** [comment]
The LaTeX3 functions and variables are not matched by the standard LaTeX grammar.
Note that in the previous LaTeX3 dedicated grammar, functions were assigned the `keyword.control.expl.latex` scope, which was wrong. Now, we use the scope `support.function.general.tex` as for other LaTeX macros.

**Comment by SwitWu** [comment]
Hi@jlelong Currently the syntax highlighting is still wrong. The last updated time of the extension is 2024-04-21, 19:09:54.

<img width="1124" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/e7e744e4-fd99-49da-be99-22c9d1f39519">
<img width="1026" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/a1eb031b-ad0b-40bf-92f3-59bd5468aaea">

And the syntax highlighting of  dtx files is also strange and  wrong. See this screenshot:

<img width="1096" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/c9219cad-5e93-4edd-9e01-289a5a9a7130">

**Comment by jlelong** [comment]
I do not know what the last updated time refers to but the fix has not been released yet. Version `9.20.0` was released a week ago. Using the development version of the extension

<img width="338" alt="Capture d’écran 2024-04-22 à 06 49 34" src="https://github.com/jlelong/vscode-latex-basics/assets/2910140/6c8870f4-4ec0-4d97-a0d1-3a61cc1500e9">

<img width="144" alt="Capture d’écran 2024-04-22 à 06 50 30" src="https://github.com/jlelong/vscode-latex-basics/assets/2910140/09ac8aa7-fcbb-474b-8609-70b381cac99e">

**Comment by SwitWu** [comment]
How to use the development version?

**Comment by jlelong** [comment]
You can download the `.zip` artifact https://github.com/James-Yu/LaTeX-Workshop/actions/runs/8767494435/artifacts/1432332965. You can install the contained `.vsix` package, using _Extensions: Install from VSIX_.

**Comment by SwitWu** [comment]
Thanks for the guide. After installing from VSIX, there is some problems.

<img width="677" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/7c112e73-ce42-4e32-b553-97014a464d50">

`\__module_foo:nn` is not highlighted correctly.

And another strange phenomenon:

<img width="406" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/ee502794-40af-46c6-9c7d-bf34bc289d8d">

**Comment by jlelong** [comment]
The LaTeX3 grammar is built from the conventions described in section 1.1 of https://ctan.math.illinois.edu/macros/latex/contrib/l3kernel/interface3.pdf

In particular, it is written that _Each function name starts with the module to which it belongs_. So a function should not start with a double `_`, but it could be changed.

This issue on the `.dtx` file is most likely related to the fix of #83 https://github.com/jlelong/vscode-latex-basics/commit/4f8b49bca02b0bfde6e46252c209396ba6c567f9. Can you open a new issue on this? Thanks

**Comment by SwitWu** [comment]
The [expl3.pdf](https://ctan.math.illinois.edu/macros/latex/contrib/l3kernel/expl3.pdf) says that:

> To allow clear separation of these two cases, the following convention is used. To denote a private function or a private variable (of the module), two `_` characters are used in front of the module name, e.g.
>  ```
> \module_foo:nnn
>  ```
>  is a public function which should be documented while
> ```
> \__module_foo:nnn
> ```
> is private to the module, and should *not* be used outside of that module.

So it is reasonable for a function name to be started with `\__`.


> This issue on the .dtx file is most likely related to the fix of https://github.com/jlelong/vscode-latex-basics/issues/83 https://github.com/jlelong/vscode-latex-basics/commit/4f8b49bca02b0bfde6e46252c209396ba6c567f9. Can you open a new issue on this? Thanks

OK. I'll open a new issue.
