### ISSUE TITLE
environments cause erroneous syntax highlighting in dtx file

### ISSUE THREAD

**Issue by SwitWu** [jlelong/vscode-latex-basics#85]
### A clear and concise description of what the bug is.

After testing in a lot of cases, I found that the first environment (whatever it is, defined or undefined) in dtx file will cause all lines after it to be highlighted erroneously.

### A minimal example to reproduce the issue

test this file
```
% \iffalse
%<*driver>
\documentclass{whudoc}
\begin{document}
  \DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
%
% \title{title}
% \author{author}
% \date{\today}
% \maketitle
% \tableofcontents
% \begin{tikzpicture}
%   some code
% \end{tikzpicture}
% some code
% \TeX \LaTeX abcd
```
<img width="393" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/fae5153b-c85e-4096-8332-7f70477d9d2e">

Replace the `tikzpicture` with anything else and see the result. It is the same.

- VS Code Version: 1.88.1 (Universal)
- OS Version: macOS 14.4.1
- LaTeX-Workshop version if you use it: v9.20.0

**Comment by jlelong** [comment]
This is related to the use of `$self` instead of `$base` in the LaTeX grammar. See #83
I have to think of it in depth but the only solution is probably to duplicate the LaTeX grammar inside the doctex one.

**Comment by SwitWu** [comment]
Thanks. When will the new `.vsix` package be generated?

**Comment by jlelong** [comment]
You can try https://github.com/James-Yu/LaTeX-Workshop/actions/runs/8937707565/artifacts/1470267334
