### ISSUE TITLE
Refactoring grammar development

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#86]
@James-Yu 

Currently, this repo only contains the TeX, LaTeX and BibTeX grammars. They are only ones built in VS Code. I think we should move all the grammars to this repo for the ease of maintenance and testing. Then, LaTeX-workshop would only pull the grammars and language configurations from this repo. 

In particular, fixing #85 will certainly require to duplicate the LaTeX grammar inside the doctex one. This has to be done inside the building tools as we do in [build-md.js](https://github.com/jlelong/vscode-latex-basics/blob/c787db94a56bd93131ce0938046063320a02cc73/build/latex-md.js)

Do you agree with this change?

**Comment by James-Yu** [comment]
I am absolutely fine with that!
