### ISSUE TITLE
expl3 functions whose names start with underscore are not highlighted correctly

### ISSUE THREAD

**Issue by SwitWu** [jlelong/vscode-latex-basics#89]
### A clear and concise description of what the bug is.

In fact, the first problem in the following list has been reported in #84 but it is closed. So I think I should mention it again here.

1. expl3 functions whose names start with underscore are not highlighted correctly
2. functions in `\keys_define` block are not highlighted at all.

### A minimal example to reproduce the issue

```tex
\module_foo:nn
\_module_foo:nn
\__module_foo:nn

\keys_define:nn { module / option }
  {
    type .choice:,
    type .value_required:n = true,
    type .initial:n = bachelor,
  }
```

<img width="516" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/fdb561cb-b6e0-49bd-a738-f2ab9ce45662">

- VS Code Version: 1.88.1 (Universal)
- OS Version: macOS Sonoma 14.4.1
- LaTeX-Workshop version if you use it: 9.20.1

**Comment by jlelong** [comment]
I will fix the leading underscores issue.

What kind of highlighting do you expect for the block  
```
  {
    type .choice:,
    type .value_required:n = true,
    type .initial:n = bachelor,
  }
```

Do you have a reference document on this syntax? What about the leading `.`?

**Comment by SwitWu** [comment]
> Do you have a reference document on this syntax? What about the leading `.`?

The interface3 manual calls these terms (`.choice:`, `.value_required:n`, `.initial:n`) as key properties. In fact, they are very similar to expl3 functions, with the leading `\` replaced by `.`.

If I test with [latexworkshop v9.19.1](https://github.com/James-Yu/LaTeX-Workshop/actions/runs/8442682539), the effect is pretty nice:

<img width="573" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/b6a33abd-ffcc-4dfe-81b2-f1d0647211f6">

I can't recall from which version on this syntax highlighting is not supported anymore.

**Comment by jlelong** [comment]
@SwitWu Can you try https://github.com/James-Yu/LaTeX-Workshop/actions/runs/8951185844/artifacts/1473159767?

**Comment by SwitWu** [comment]
@jlelong I’ll try it tomorrow, thank you for the quick fix.

**Comment by SwitWu** [comment]
The result is as expected. BTW, how to change the color of expl3 functions and key properties to:

<img width="383" alt="image" src="https://github.com/jlelong/vscode-latex-basics/assets/39337667/f976e932-f84e-4dd3-8230-120bb6100d74">

as shown in 

![image](https://github.com/jlelong/vscode-latex-basics/assets/39337667/801ce3b7-fb17-4757-b679-7aeafbe731d0)

**Comment by jlelong** [comment]
Sorry for the silence. For the time being, all macros (classical LaTeX ones and LaTeX3 macros) are assigned the same scope `support.function.general.tex`. To change its color to red for instance, you need to add to your `settings.json` file

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "support.function.general.tex",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
```

It may make sense to differentiate the scopes assigned to LaTeX3 functions from the one used for standard LaTeX macros. what do you think?

**Comment by SwitWu** [comment]
> It may make sense to differentiate the scopes assigned to LaTeX3 functions from the one used for standard LaTeX macros. what do you think?

I agree with this.

**Comment by jlelong** [comment]
The new scope for latex3 functions is `support.class.general.latex3.tex`.

**Comment by SwitWu** [comment]
> The new scope for latex3 functions is `support.class.general.latex3.tex`.

OK. Looking forward to the new version. Thank you!
