### ISSUE TITLE
#7 has made it impossible to apply different colors to inline math and math environment

### ISSUE THREAD

**Issue by tamuratak** [jlelong/vscode-latex-basics#9]
#7 has made it impossible to apply different colors to inline math and math environment.

Inline math is classified as `support.class.math.block.environment.latex` now although it was `support.class.math.block.tex` before.

#7 changes syntax tree too much to fix a relatively minor issue.

**Comment by jlelong** [comment]
#10 sets the previous scope back while solving #7. Can you check that everything is fine for you with #10?

Note that LaTeX inline math `\(...\)` already has scope `support.class.math.block.environment.latex` as displayed math. I thought it was better to use the same scope for TeX inline math `$...$` and `\(...\)` but apparently you do not.

**Comment by tamuratak** [comment]
I have confirmed that #10 works. Thank you.

> Note that LaTeX inline math \(...\) already has scope support.class.math.block.environment.latex as displayed math. 

I haven't known it.
