### ISSUE TITLE
Highlighting of `\parencites` with `multiprenote` and/or `multipostnote` 

### ISSUE THREAD

**Issue by jlelong** [jlelong/vscode-latex-basics#93]
Originally posted by @ postylem in James-Yu/LaTeX-Workshop#4313

The version with multiprenote and/or multipostnote (which are in parentheses) of `\parencites` (biblatex) is not supported:

```
\parencites(multipre)(multipost)[pre][post]{bibid}[pre][post]{bibid} 
```

<img width="693" alt="346290699-5e09e523-a268-4f23-a01a-0f91681292b7" src="https://github.com/jlelong/vscode-latex-basics/assets/2910140/9fa6ea3b-1878-460b-8b05-bce9c8a14f2a">

**Comment by postylem** [comment]
Thanks for picking this up! Just to be clear, as noted in the image above, there’s a highlighting issue _even without_ the multiprenote/multipostnote args: Note the second (and subsequent) bibids are not highlighted, only the first is. And when the parenthetical args _are_ included, none are highlighted.
